version: "3.7"

services:
  postgres:
    container_name: pulsar-postgres
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pulsar
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
